import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { useState } from "react";

const inter = Inter({ subsets: ["latin"] });

export default function Home({ wordFrequency }) {
  const [viewSubmit, setViewSubmit] = useState(true);
  const [histogramData, setHistogramData] = useState([]);
  const handleSubmit = async () => {
    const response = await fetch("https://www.terriblytinytales.com/test.txt");
    const text = await response.text();
    const words = text.split(/\s+/);

    const wordFrequency = {};
    for (const word of words) {
      if (wordFrequency[word]) {
        wordFrequency[word]++;
      } else {
        wordFrequency[word] = 1;
      }
    }

    const sortedWords = Object.keys(wordFrequency).sort(
      (a, b) => wordFrequency[b] - wordFrequency[a]
    );

    const top20Words = sortedWords.slice(0, 20);
    const histogramData = top20Words.map((word) => ({
      word,
      frequency: wordFrequency[word],
    }));

    setHistogramData(histogramData);
    setViewSubmit(false);
  };

  const handleExport = () => {
    const csvContent = "data:text/csv;charset=utf-8," + [
      ["Word", "Frequency"],
      ...histogramData.map(({ word, frequency }) => [word, frequency]),
    ]
      .map((row) => row.join(","))
      .join("\n");

    const encodedUri = encodeURI(csvContent);
    const link = document.createElement("a");
    link.setAttribute("href", encodedUri);
    link.setAttribute("download", "histogram.csv");
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  return (
    <>
      <Head>
        <title>Assignment</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        {viewSubmit && (
          <button
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
            onClick={handleSubmit}
          >
            <h1 className={inter.className}>
              Submit <span>-&gt;</span>
            </h1>
          </button>
        )}
        {!viewSubmit && (
          <>
            <h1>Word Frequency Histogram</h1>
            <div className={styles.histogram}>
              {histogramData.map(({ word, frequency }) => (
                <div key={word} className={styles.histogramBar}>
                  <div className={styles.histogramBarLabel}>{word}</div>
                  <div
                    className={styles.histogramBarValue}
                    style={{ width: `${(frequency / histogramData[0].frequency) * 100}%` }}
                  ></div>
                  <div className={styles.histogramBarFrequency}>{frequency}</div>
                </div>
              ))}
            </div>
            <button className={styles.exportButton} onClick={handleExport}>
              Export
            </button>
          </>
        )}
      </main>
    </>
  );
}

export async function getServerSideProps() {
  return {
    props: {
      wordFrequency: {},
    },
  };
}
