import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { useState } from "react";

const inter = Inter({ subsets: ["latin"] });

export default function Home({wordFrequency}) {
  const [viewSubmit, setViewSubmit] = useState(true);
  const handleSubmit =()=>{
    console.log(wordFrequency)
    setViewSubmit(false)
  }
  return (
    <>
      <Head>
        <title>Assignment</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        {viewSubmit && (
          <button
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
            onClick={handleSubmit}
          >
            <h1 className={inter.className}>
              Submit <span>-&gt;</span>
            </h1>
          </button>
        )}
      </main>
    </>
  );
}
export async function getServerSideProps() {
  // Fetch the contents of the text file
  const response = await fetch('https://www.terriblytinytales.com/test.txt');
  const text = await response.text();
  console.log(text);
  // Split the text into an array of words
  const words = text.split(/\s+/);

  // Create an object to store the frequency of each word
  const wordFrequency = {};

  // Iterate over the array of words and count the frequency of each word
  for (const word of words) {
    if (wordFrequency[word]) {
      wordFrequency[word]++;
    } else {
      wordFrequency[word] = 1;
    }
  }

  // Return the result as props
  return {
    props: {
      wordFrequency,
    },
  };
}

